apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rag-media-pvc
  namespace: rag-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
