# Generated by Django 5.2 on 2025-09-14 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('image', '이미지'), ('text', '텍스트'), ('audio', '음성')], max_length=20, verbose_name='데이터 타입')),
                ('object_id', models.PositiveIntegerField(verbose_name='객체 ID')),
                ('process_type', models.CharField(max_length=50, verbose_name='처리 타입')),
                ('status', models.CharField(choices=[('success', '성공'), ('error', '실패')], max_length=20, verbose_name='처리 결과')),
                ('message', models.TextField(blank=True, verbose_name='처리 메시지')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '처리 로그',
                'verbose_name_plural': '처리 로그',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AudioData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('audio_file', models.FileField(upload_to='audio/', verbose_name='음성 파일')),
                ('transcribed_text', models.TextField(blank=True, verbose_name='변환된 텍스트')),
                ('extracted_keywords', models.JSONField(default=list, verbose_name='추출된 키워드')),
                ('processing_status', models.CharField(choices=[('pending', '처리 대기'), ('processing', '처리 중'), ('completed', '완료'), ('error', '오류')], default='pending', max_length=20, verbose_name='처리 상태')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '음성 데이터',
                'verbose_name_plural': '음성 데이터',
            },
        ),
        migrations.CreateModel(
            name='ImageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('image_file', models.ImageField(upload_to='images/', verbose_name='이미지 파일')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드 시간')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '이미지 데이터',
                'verbose_name_plural': '이미지 데이터',
            },
        ),
        migrations.CreateModel(
            name='ImageSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='객체 라벨 (음식 종류)')),
                ('coordinates', models.JSONField(verbose_name='세그먼트 좌표 정보')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='multimodal.imagedata')),
            ],
            options={
                'verbose_name': '이미지 세그먼트',
                'verbose_name_plural': '이미지 세그먼트',
            },
        ),
        migrations.CreateModel(
            name='TextData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('original_text', models.TextField(verbose_name='원본 텍스트')),
                ('processed_text', models.TextField(blank=True, verbose_name='처리된 텍스트')),
                ('morphemes', models.JSONField(default=list, verbose_name='형태소 분석 결과')),
                ('keywords', models.JSONField(default=list, verbose_name='키워드 추출 결과')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '텍스트 데이터',
                'verbose_name_plural': '텍스트 데이터',
            },
        ),
    ]
